(module
   (func $textToNumber(param $size i32)(result i32)
        (local $number i32)
        (local $parameter i32)
        (local.set $number (i32.const 0))
        (local.set $parameter (i32.const 1))
        (loop $numberization
             (local $character i32)
             (local.set $character (local.get (local.get $parameter)))
             (local.set $number (i32.add (i32.mul local.get $number(i32.const 126))(local.get $character))
             (local.set $parameter (i32.add (local.get $parameter)(i32.const 1)))
             (i32.lt (local.get $parameter)(local.get $size))
             (br_if $numberization)
        )
        (local.get $number)
   )
   (func $placeData (param $count i32)
      (local $parameter i32)
      (local.set $parameter (i32.const 1))
      (local $address i32)
      (local.set $address (i32.const 0))
      (loop $placement
        (local $value i32)
        (local.set $value (local.get ((i32.add local.get $parameter (i32.const 1))))
        (local $typeCode i32)
        (local.set $typeCode (local.get (i32.add local.get $parameter (i32.const 2))))
        (i32.store (local.get $address) (local.get (local.get $parameter)))
        (if (i32.eq local.get $typeCode (i32.const 68));;Ascii for "D" for Double
        (then
              (f32.store ((i32.add local.get $address (i32.const 256))(local.get $value))
          )(else
              (i32.store ((i32.add local.get $address (i32.const 256))(local.get $value))
          ))
        (i32.store ((i32.add local.get $address (i32.const 256))(local.get $value) )
        (i32.store ((i32.add local.get $address (i32.const 512)) )
         (local.set $address (i32.add (local.get $address)(i32.const 776)))
          (local.set $parameter (local.get $parameter)(i32.const 3))
           (i32.lt (local.get $parameter)(local.get $count))
             (br_if $placement)
      )
 )      